name: Update Flake Inputs

concurrency:
  group: nix-flake
  cancel-in-progress: false

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  update-and-setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update flake inputs
        run: nix flake update

      - name: Run nix flake check
        run: nix flake check

      - name: Generate host matrix
        id: set-matrix
        run: |
          HOSTS=$(nix eval .#nixosConfigurations --apply builtins.attrNames --json)
          echo "matrix=$HOSTS" >> $GITHUB_OUTPUT

      - name: Upload updated flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: flake-lock
          path: flake.lock
          retention-days: 1

  evaluate:
    needs: update-and-setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        host: ${{ fromJson(needs.update-and-setup.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download updated flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake-lock
          path: .

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Use magic nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Evaluate NixOS Configuration (${{ matrix.host }})
        run: nix build --dry-run ".#nixosConfigurations.\"${{ matrix.host }}\".config.system.build.toplevel"

  commit-update:
    needs: evaluate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download updated flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake-lock
          path: .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update flake lock file"
          file_pattern: "flake.lock"
